### ISSUE TITLE
arithmetic overflow when parsing str → Json

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang-nursery/rustc-serialize#109]
Attempting to parse:

```
{"":"","":{"":"","":[{"":""},-0
```

Results in:

```
root@afl-rust:~/afl-staging-area# cargo run < outputs/crashes/new
     Running `target/debug/afl-staging-area`
thread '<main>' panicked at 'arithmetic operation overflowed', /root/rustc-serialize/src/json.rs:1488
An unknown error occurred
```

This bug was found using https://github.com/kmcallister/afl.rs 👍

**Comment by frewsxcv** [comment]
Here's the code I used:

```rust
extern crate rustc_serialize;

use rustc_serialize::json::Json;

use std::io::{self, Read, Cursor};

fn main() {
    let mut input = String::new();
    let result = io::stdin().read_to_string(&mut input);
    if result.is_ok() {
        let data = Json::from_str(&input);
    }
}
```

And the log/backtrace:

```
DEBUG:cargo::build: executing; cmd=cargo-build; args=["cargo", "build"]
DEBUG:cargo::ops::cargo_compile: compile; manifest-path=/private/tmp/hi/Cargo.toml
DEBUG:cargo::ops::cargo_compile: loaded package; package=hi v0.1.0 (file:///private/tmp/hi)
DEBUG:cargo::ops::cargo_compile: loaded config; configs={"registry": {"token": y8Q6qDz21k86bKpW2e5kPzFIwugLeq2q (from /Users/coreyf/.cargo/config)}}
DEBUG:cargo::core::resolver: activating hi v0.1.0 (file:///private/tmp/hi)
DEBUG:cargo::core::registry: load/missing  https://github.com/rust-lang/rustc-serialize#af910b74
INFO:cargo::sources::git::utils: update submodules for: "/Users/coreyf/.cargo/git/checkouts/rustc-serialize-bdc70357aa712c7d/master/"
DEBUG:cargo::core::resolver: activating rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
DEBUG:cargo::core::resolver: resolved: graph: Graph {
  - rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
  - hi v0.1.0 (file:///private/tmp/hi)
    - rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
}

features: {
}
DEBUG:cargo::core::resolver: activating hi v0.1.0 (file:///private/tmp/hi)
DEBUG:cargo::core::registry: load/match    https://github.com/rust-lang/rustc-serialize#af910b74
DEBUG:cargo::core::resolver: activating rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
DEBUG:cargo::core::resolver: resolved: graph: Graph {
  - rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
  - hi v0.1.0 (file:///private/tmp/hi)
    - rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
}

features: {
}
DEBUG:cargo::ops::cargo_rustc: compile_targets: hi v0.1.0 (file:///private/tmp/hi)
DEBUG:cargo::ops::cargo_rustc: compile_pkg; pkg=hi v0.1.0 (file:///private/tmp/hi)
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /private/tmp/hi/target/debug/.fingerprint/hi-585ac5373ba9154b/bin-hi
DEBUG:cargo::ops::cargo_rustc::fingerprint: extra Target { kind: Bin, name: "hi", src_path: "/private/tmp/hi/src/main.rs", metadata: None, tested: true, benched: true, doc: true, doctest: false, harness: true, for_host: false } Profile { opt_level: 0, lto: false, codegen_units: None, rustc_args: None, debuginfo: true, debug_assertions: true, rpath: false, test: false, doc: false } None = 0553f1644cff0529
DEBUG:cargo::ops::cargo_rustc::fingerprint: extra Target { kind: Lib([Lib]), name: "rustc-serialize", src_path: "/Users/coreyf/.cargo/git/checkouts/rustc-serialize-bdc70357aa712c7d/master/src/lib.rs", metadata: Some(Metadata { metadata: "d9cf16782a5152b9", extra_filename: "-d9cf16782a5152b9" }), tested: true, benched: true, doc: true, doctest: true, harness: true, for_host: false } Profile { opt_level: 0, lto: false, codegen_units: None, rustc_args: None, debuginfo: true, debug_assertions: true, rpath: false, test: false, doc: false } None = 415206d49530a1ff
DEBUG:cargo::ops::cargo_rustc::fingerprint: inputs: af910b74fbc7eb25b5e9f819af717b1abf029b34 415206d49530a1ff []
DEBUG:cargo::ops::cargo_rustc::fingerprint: inputs: 1434906638.000000000s 0553f1644cff0529 ["264fbf3ff4e1d079"]
DEBUG:cargo::ops::cargo_rustc: compile_pkg; pkg=rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /private/tmp/hi/target/debug/.fingerprint/rustc-serialize-d9cf16782a5152b9/lib-rustc-serialize
DEBUG:cargo::ops::cargo_rustc::fingerprint: inputs: af910b74fbc7eb25b5e9f819af717b1abf029b34 415206d49530a1ff []
INFO:cargo::ops::cargo_rustc::job_queue: start: hi v0.1.0 (file:///private/tmp/hi) Start
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at Start for hi v0.1.0 (file:///private/tmp/hi)
DEBUG:cargo::ops::cargo_rustc::job_queue: job: Fresh (Fresh)
INFO:cargo::ops::cargo_rustc::job_queue: start: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) Start
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at Start for rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
DEBUG:cargo::ops::cargo_rustc::job_queue: job: Fresh (Fresh)
INFO:cargo::ops::cargo_rustc::job_queue:   end: hi v0.1.0 (file:///private/tmp/hi) Start
INFO:cargo::ops::cargo_rustc::job_queue: start: hi v0.1.0 (file:///private/tmp/hi) BuildCustomBuild
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at BuildCustomBuild for hi v0.1.0 (file:///private/tmp/hi)
INFO:cargo::ops::cargo_rustc::job_queue:   end: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) Start
INFO:cargo::ops::cargo_rustc::job_queue: start: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) BuildCustomBuild
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at BuildCustomBuild for rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
INFO:cargo::ops::cargo_rustc::job_queue:   end: hi v0.1.0 (file:///private/tmp/hi) BuildCustomBuild
INFO:cargo::ops::cargo_rustc::job_queue:   end: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) BuildCustomBuild
INFO:cargo::ops::cargo_rustc::job_queue: start: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) RunCustomBuild
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at RunCustomBuild for rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
INFO:cargo::ops::cargo_rustc::job_queue:   end: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) RunCustomBuild
INFO:cargo::ops::cargo_rustc::job_queue: start: hi v0.1.0 (file:///private/tmp/hi) RunCustomBuild
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at RunCustomBuild for hi v0.1.0 (file:///private/tmp/hi)
INFO:cargo::ops::cargo_rustc::job_queue: start: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) LibraryTests
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at LibraryTests for rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
INFO:cargo::ops::cargo_rustc::job_queue: start: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) Libraries
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at Libraries for rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
DEBUG:cargo::ops::cargo_rustc::job_queue: job: Fresh (Fresh)
INFO:cargo::ops::cargo_rustc::job_queue:   end: hi v0.1.0 (file:///private/tmp/hi) RunCustomBuild
INFO:cargo::ops::cargo_rustc::job_queue:   end: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) LibraryTests
INFO:cargo::ops::cargo_rustc::job_queue:   end: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) Libraries
INFO:cargo::ops::cargo_rustc::job_queue: start: hi v0.1.0 (file:///private/tmp/hi) Libraries
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at Libraries for hi v0.1.0 (file:///private/tmp/hi)
INFO:cargo::ops::cargo_rustc::job_queue: start: hi v0.1.0 (file:///private/tmp/hi) LibraryTests
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at LibraryTests for hi v0.1.0 (file:///private/tmp/hi)
INFO:cargo::ops::cargo_rustc::job_queue: start: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) BinaryTests
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at BinaryTests for rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
INFO:cargo::ops::cargo_rustc::job_queue: start: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) Binaries
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at Binaries for rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
INFO:cargo::ops::cargo_rustc::job_queue:   end: hi v0.1.0 (file:///private/tmp/hi) Libraries
INFO:cargo::ops::cargo_rustc::job_queue: start: hi v0.1.0 (file:///private/tmp/hi) Binaries
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at Binaries for hi v0.1.0 (file:///private/tmp/hi)
DEBUG:cargo::ops::cargo_rustc::job_queue: job: Fresh (Fresh)
INFO:cargo::ops::cargo_rustc::job_queue: start: hi v0.1.0 (file:///private/tmp/hi) BinaryTests
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at BinaryTests for hi v0.1.0 (file:///private/tmp/hi)
INFO:cargo::ops::cargo_rustc::job_queue:   end: hi v0.1.0 (file:///private/tmp/hi) LibraryTests
INFO:cargo::ops::cargo_rustc::job_queue:   end: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) BinaryTests
INFO:cargo::ops::cargo_rustc::job_queue:   end: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) Binaries
INFO:cargo::ops::cargo_rustc::job_queue: start: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) End
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at End for rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
INFO:cargo::ops::cargo_rustc::job_queue:   end: hi v0.1.0 (file:///private/tmp/hi) Binaries
INFO:cargo::ops::cargo_rustc::job_queue:   end: hi v0.1.0 (file:///private/tmp/hi) BinaryTests
INFO:cargo::ops::cargo_rustc::job_queue: start: hi v0.1.0 (file:///private/tmp/hi) End
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at End for hi v0.1.0 (file:///private/tmp/hi)
INFO:cargo::ops::cargo_rustc::job_queue:   end: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) End
INFO:cargo::ops::cargo_rustc::job_queue:   end: hi v0.1.0 (file:///private/tmp/hi) End
DEBUG:cargo::ops::cargo_compile: compile; manifest-path=/private/tmp/hi/Cargo.toml
DEBUG:cargo::ops::cargo_compile: loaded package; package=hi v0.1.0 (file:///private/tmp/hi)
DEBUG:cargo::ops::cargo_compile: loaded config; configs={"registry": {"token": y8Q6qDz21k86bKpW2e5kPzFIwugLeq2q (from /Users/coreyf/.cargo/config)}}
DEBUG:cargo::core::resolver: activating hi v0.1.0 (file:///private/tmp/hi)
DEBUG:cargo::core::registry: load/missing  https://github.com/rust-lang/rustc-serialize#af910b74
INFO:cargo::sources::git::utils: update submodules for: "/Users/coreyf/.cargo/git/checkouts/rustc-serialize-bdc70357aa712c7d/master/"
DEBUG:cargo::core::resolver: activating rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
DEBUG:cargo::core::resolver: resolved: graph: Graph {
  - rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
  - hi v0.1.0 (file:///private/tmp/hi)
    - rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
}

features: {
}
DEBUG:cargo::core::resolver: activating hi v0.1.0 (file:///private/tmp/hi)
DEBUG:cargo::core::registry: load/match    https://github.com/rust-lang/rustc-serialize#af910b74
DEBUG:cargo::core::resolver: activating rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
DEBUG:cargo::core::resolver: resolved: graph: Graph {
  - rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
  - hi v0.1.0 (file:///private/tmp/hi)
    - rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
}

features: {
}
DEBUG:cargo::ops::cargo_rustc: compile_targets: hi v0.1.0 (file:///private/tmp/hi)
DEBUG:cargo::ops::cargo_rustc: compile_pkg; pkg=hi v0.1.0 (file:///private/tmp/hi)
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /private/tmp/hi/target/debug/.fingerprint/hi-585ac5373ba9154b/bin-hi
DEBUG:cargo::ops::cargo_rustc::fingerprint: extra Target { kind: Bin, name: "hi", src_path: "/private/tmp/hi/src/main.rs", metadata: None, tested: true, benched: true, doc: true, doctest: false, harness: true, for_host: false } Profile { opt_level: 0, lto: false, codegen_units: None, rustc_args: None, debuginfo: true, debug_assertions: true, rpath: false, test: false, doc: false } None = 0553f1644cff0529
DEBUG:cargo::ops::cargo_rustc::fingerprint: extra Target { kind: Lib([Lib]), name: "rustc-serialize", src_path: "/Users/coreyf/.cargo/git/checkouts/rustc-serialize-bdc70357aa712c7d/master/src/lib.rs", metadata: Some(Metadata { metadata: "d9cf16782a5152b9", extra_filename: "-d9cf16782a5152b9" }), tested: true, benched: true, doc: true, doctest: true, harness: true, for_host: false } Profile { opt_level: 0, lto: false, codegen_units: None, rustc_args: None, debuginfo: true, debug_assertions: true, rpath: false, test: false, doc: false } None = 415206d49530a1ff
DEBUG:cargo::ops::cargo_rustc::fingerprint: inputs: af910b74fbc7eb25b5e9f819af717b1abf029b34 415206d49530a1ff []
DEBUG:cargo::ops::cargo_rustc::fingerprint: inputs: 1434906638.000000000s 0553f1644cff0529 ["264fbf3ff4e1d079"]
DEBUG:cargo::ops::cargo_rustc: compile_pkg; pkg=rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /private/tmp/hi/target/debug/.fingerprint/rustc-serialize-d9cf16782a5152b9/lib-rustc-serialize
DEBUG:cargo::ops::cargo_rustc::fingerprint: inputs: af910b74fbc7eb25b5e9f819af717b1abf029b34 415206d49530a1ff []
INFO:cargo::ops::cargo_rustc::job_queue: start: hi v0.1.0 (file:///private/tmp/hi) Start
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at Start for hi v0.1.0 (file:///private/tmp/hi)
DEBUG:cargo::ops::cargo_rustc::job_queue: job: Fresh (Fresh)
INFO:cargo::ops::cargo_rustc::job_queue: start: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) Start
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at Start for rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
DEBUG:cargo::ops::cargo_rustc::job_queue: job: Fresh (Fresh)
INFO:cargo::ops::cargo_rustc::job_queue:   end: hi v0.1.0 (file:///private/tmp/hi) Start
INFO:cargo::ops::cargo_rustc::job_queue: start: hi v0.1.0 (file:///private/tmp/hi) BuildCustomBuild
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at BuildCustomBuild for hi v0.1.0 (file:///private/tmp/hi)
INFO:cargo::ops::cargo_rustc::job_queue:   end: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) Start
INFO:cargo::ops::cargo_rustc::job_queue: start: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) BuildCustomBuild
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at BuildCustomBuild for rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
INFO:cargo::ops::cargo_rustc::job_queue:   end: hi v0.1.0 (file:///private/tmp/hi) BuildCustomBuild
INFO:cargo::ops::cargo_rustc::job_queue:   end: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) BuildCustomBuild
INFO:cargo::ops::cargo_rustc::job_queue: start: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) RunCustomBuild
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at RunCustomBuild for rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
INFO:cargo::ops::cargo_rustc::job_queue:   end: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) RunCustomBuild
INFO:cargo::ops::cargo_rustc::job_queue: start: hi v0.1.0 (file:///private/tmp/hi) RunCustomBuild
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at RunCustomBuild for hi v0.1.0 (file:///private/tmp/hi)
INFO:cargo::ops::cargo_rustc::job_queue: start: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) LibraryTests
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at LibraryTests for rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
INFO:cargo::ops::cargo_rustc::job_queue: start: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) Libraries
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at Libraries for rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
DEBUG:cargo::ops::cargo_rustc::job_queue: job: Fresh (Fresh)
INFO:cargo::ops::cargo_rustc::job_queue:   end: hi v0.1.0 (file:///private/tmp/hi) RunCustomBuild
INFO:cargo::ops::cargo_rustc::job_queue:   end: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) LibraryTests
INFO:cargo::ops::cargo_rustc::job_queue:   end: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) Libraries
INFO:cargo::ops::cargo_rustc::job_queue: start: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) BinaryTests
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at BinaryTests for rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
INFO:cargo::ops::cargo_rustc::job_queue: start: hi v0.1.0 (file:///private/tmp/hi) Libraries
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at Libraries for hi v0.1.0 (file:///private/tmp/hi)
INFO:cargo::ops::cargo_rustc::job_queue: start: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) Binaries
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at Binaries for rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
INFO:cargo::ops::cargo_rustc::job_queue: start: hi v0.1.0 (file:///private/tmp/hi) LibraryTests
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at LibraryTests for hi v0.1.0 (file:///private/tmp/hi)
INFO:cargo::ops::cargo_rustc::job_queue:   end: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) BinaryTests
INFO:cargo::ops::cargo_rustc::job_queue:   end: hi v0.1.0 (file:///private/tmp/hi) Libraries
INFO:cargo::ops::cargo_rustc::job_queue: start: hi v0.1.0 (file:///private/tmp/hi) Binaries
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at Binaries for hi v0.1.0 (file:///private/tmp/hi)
DEBUG:cargo::ops::cargo_rustc::job_queue: job: Fresh (Fresh)
INFO:cargo::ops::cargo_rustc::job_queue: start: hi v0.1.0 (file:///private/tmp/hi) BinaryTests
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at BinaryTests for hi v0.1.0 (file:///private/tmp/hi)
INFO:cargo::ops::cargo_rustc::job_queue:   end: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) Binaries
INFO:cargo::ops::cargo_rustc::job_queue: start: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) End
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at End for rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
INFO:cargo::ops::cargo_rustc::job_queue:   end: hi v0.1.0 (file:///private/tmp/hi) LibraryTests
INFO:cargo::ops::cargo_rustc::job_queue:   end: hi v0.1.0 (file:///private/tmp/hi) Binaries
INFO:cargo::ops::cargo_rustc::job_queue:   end: hi v0.1.0 (file:///private/tmp/hi) BinaryTests
INFO:cargo::ops::cargo_rustc::job_queue: start: hi v0.1.0 (file:///private/tmp/hi) End
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at End for hi v0.1.0 (file:///private/tmp/hi)
INFO:cargo::ops::cargo_rustc::job_queue:   end: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) End
INFO:cargo::ops::cargo_rustc::job_queue:   end: hi v0.1.0 (file:///private/tmp/hi) End
     Running `target/debug/hi`
thread '<main>' panicked at 'arithmetic operation overflowed', /Users/coreyf/.cargo/git/checkouts/rustc-serialize-bdc70357aa712c7d/master/src/json.rs:1488
stack backtrace:
   1:        0x10ffbae45 - sys::backtrace::write::hb40a7a5e7a72988bfas
   2:        0x10ffbdff4 - panicking::on_panic::h86479ea026bd45advvw
   3:        0x10ffb7cb8 - rt::unwind::begin_unwind_inner::h293827e692145ff2Ndw
   4:        0x10ffb7fbc - rt::unwind::begin_unwind_fmt::h50405e2d93950933Tcw
   5:        0x10ffbd8ac - rust_begin_unwind
   6:        0x10ffdd705 - panicking::panic_fmt::he351326af800e539i5B
   7:        0x10ffdaa24 - panicking::panic::he4a0099d61967bb4P3B
   8:        0x10ffa7730 - json::Parser<T>::parse_number::h2869670053614061741
   9:        0x10ffa68ea - json::Parser<T>::parse_value::h10240053483430817318
  10:        0x10ffa9664 - json::Parser<T>::parse_array::h1943645362353975016
  11:        0x10ffa642b - json::Parser<T>::parse::h15677379941937867546
  12:        0x10ffa5e06 - json::Parser<T>.Iterator::next::h11324056002650123987
  13:        0x10ffa5c90 - json::Builder<T>::bump::h6672005551472268718
  14:        0x10ffab323 - json::Builder<T>::build_array::h11864918996972364087
  15:        0x10ffaa809 - json::Builder<T>::build_value::h15461967774057179667
  16:        0x10ffad190 - json::Builder<T>::build_object::h16833853255729959591
  17:        0x10ffaa81e - json::Builder<T>::build_value::h15461967774057179667
  18:        0x10ffad190 - json::Builder<T>::build_object::h16833853255729959591
  19:        0x10ffaa81e - json::Builder<T>::build_value::h15461967774057179667
  20:        0x10ffa5961 - json::Builder<T>::build::h9608899132882922979
  21:        0x10ffb56c2 - json::Json::from_str::hf3f63141a48a0bf0X9k
  22:        0x10ff94b89 - main::h781db2a45f4d5b0fkaa
  23:        0x10ffbf008 - rust_try_inner
  24:        0x10ffbeff5 - rust_try
  25:        0x10ffbe800 - rt::lang_start::h1547a6a6590823a3zqw
  26:        0x10ff9a66e - main
DEBUG:cargo: handle_error; err=CliError { error: Process didn't exit successfully: `target/debug/hi` (exit code: 101), unknown: true, exit_code: 101 }
An unknown error occurred

To learn more, run the command again with --verbose.
```

**Comment by mrpink76** [comment]
Seem to be the -0 that is not handled correctly, had the same problem with the following json:
{"on":true,"volume":-0,"mode":"","input":""}

Panic message was:
panicked at 'arithmetic operation overflowed', /home/petter/.cargo/registry/src/github.com-88ac128001ac3a9a/rustc-serialize-0.3.16/src/json.rs:1496
