### ISSUE TITLE
Some(ObjectEnd) panic when parsing str → Json

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang-nursery/rustc-serialize#110]
Attempting to parse:

```
{"":"","":{"":"","":[{"":"",}}}
```

Results in:

```
root@afl-rust:~/afl-staging-area# cargo run < outputs/crashes/new2
     Running `target/debug/afl-staging-area`
thread '<main>' panicked at 'unexpected token Some(ObjectEnd)', /root/rustc-serialize/src/json.rs:1927
An unknown error occurred
```

This bug was found using https://github.com/kmcallister/afl.rs 👍

**Comment by manuels** [comment]
Could you provide the output of `RUST_LOG=debug RUST_BACKTRACE=1 cargo run < outputs/crashes/new2`?

**Comment by frewsxcv** [comment]
Here's the code I used:

```rust
extern crate rustc_serialize;

use rustc_serialize::json::Json;

use std::io::{self, Read, Cursor};

fn main() {
    let mut input = String::new();
    let result = io::stdin().read_to_string(&mut input);
    if result.is_ok() {
        let data = Json::from_str(&input);
    }
}
```

And the log/backtrace:

```
DEBUG:cargo::build: executing; cmd=cargo-build; args=["cargo", "build"]
DEBUG:cargo::ops::cargo_compile: compile; manifest-path=/private/tmp/hi/Cargo.toml
DEBUG:cargo::ops::cargo_compile: loaded package; package=hi v0.1.0 (file:///private/tmp/hi)
DEBUG:cargo::ops::cargo_compile: loaded config; configs={"registry": {"token": y8Q6qDz21k86bKpW2e5kPzFIwugLeq2q (from /Users/coreyf/.cargo/config)}}
DEBUG:cargo::core::resolver: activating hi v0.1.0 (file:///private/tmp/hi)
DEBUG:cargo::core::registry: load/missing  https://github.com/rust-lang/rustc-serialize#af910b74
INFO:cargo::sources::git::utils: update submodules for: "/Users/coreyf/.cargo/git/checkouts/rustc-serialize-bdc70357aa712c7d/master/"
DEBUG:cargo::core::resolver: activating rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
DEBUG:cargo::core::resolver: resolved: graph: Graph {
  - hi v0.1.0 (file:///private/tmp/hi)
    - rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
  - rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
}

features: {
}
DEBUG:cargo::core::resolver: activating hi v0.1.0 (file:///private/tmp/hi)
DEBUG:cargo::core::registry: load/match    https://github.com/rust-lang/rustc-serialize#af910b74
DEBUG:cargo::core::resolver: activating rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
DEBUG:cargo::core::resolver: resolved: graph: Graph {
  - hi v0.1.0 (file:///private/tmp/hi)
    - rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
  - rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
}

features: {
}
DEBUG:cargo::ops::cargo_rustc: compile_targets: hi v0.1.0 (file:///private/tmp/hi)
DEBUG:cargo::ops::cargo_rustc: compile_pkg; pkg=hi v0.1.0 (file:///private/tmp/hi)
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /private/tmp/hi/target/debug/.fingerprint/hi-585ac5373ba9154b/bin-hi
DEBUG:cargo::ops::cargo_rustc::fingerprint: extra Target { kind: Bin, name: "hi", src_path: "/private/tmp/hi/src/main.rs", metadata: None, tested: true, benched: true, doc: true, doctest: false, harness: true, for_host: false } Profile { opt_level: 0, lto: false, codegen_units: None, rustc_args: None, debuginfo: true, debug_assertions: true, rpath: false, test: false, doc: false } None = 0553f1644cff0529
DEBUG:cargo::ops::cargo_rustc::fingerprint: extra Target { kind: Lib([Lib]), name: "rustc-serialize", src_path: "/Users/coreyf/.cargo/git/checkouts/rustc-serialize-bdc70357aa712c7d/master/src/lib.rs", metadata: Some(Metadata { metadata: "d9cf16782a5152b9", extra_filename: "-d9cf16782a5152b9" }), tested: true, benched: true, doc: true, doctest: true, harness: true, for_host: false } Profile { opt_level: 0, lto: false, codegen_units: None, rustc_args: None, debuginfo: true, debug_assertions: true, rpath: false, test: false, doc: false } None = 415206d49530a1ff
DEBUG:cargo::ops::cargo_rustc::fingerprint: inputs: af910b74fbc7eb25b5e9f819af717b1abf029b34 415206d49530a1ff []
DEBUG:cargo::ops::cargo_rustc::fingerprint: inputs: 1434906638.000000000s 0553f1644cff0529 ["264fbf3ff4e1d079"]
DEBUG:cargo::ops::cargo_rustc: compile_pkg; pkg=rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /private/tmp/hi/target/debug/.fingerprint/rustc-serialize-d9cf16782a5152b9/lib-rustc-serialize
DEBUG:cargo::ops::cargo_rustc::fingerprint: inputs: af910b74fbc7eb25b5e9f819af717b1abf029b34 415206d49530a1ff []
INFO:cargo::ops::cargo_rustc::job_queue: start: hi v0.1.0 (file:///private/tmp/hi) Start
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at Start for hi v0.1.0 (file:///private/tmp/hi)
DEBUG:cargo::ops::cargo_rustc::job_queue: job: Fresh (Fresh)
INFO:cargo::ops::cargo_rustc::job_queue: start: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) Start
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at Start for rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
DEBUG:cargo::ops::cargo_rustc::job_queue: job: Fresh (Fresh)
INFO:cargo::ops::cargo_rustc::job_queue:   end: hi v0.1.0 (file:///private/tmp/hi) Start
INFO:cargo::ops::cargo_rustc::job_queue: start: hi v0.1.0 (file:///private/tmp/hi) BuildCustomBuild
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at BuildCustomBuild for hi v0.1.0 (file:///private/tmp/hi)
INFO:cargo::ops::cargo_rustc::job_queue:   end: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) Start
INFO:cargo::ops::cargo_rustc::job_queue: start: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) BuildCustomBuild
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at BuildCustomBuild for rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
INFO:cargo::ops::cargo_rustc::job_queue:   end: hi v0.1.0 (file:///private/tmp/hi) BuildCustomBuild
INFO:cargo::ops::cargo_rustc::job_queue:   end: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) BuildCustomBuild
INFO:cargo::ops::cargo_rustc::job_queue: start: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) RunCustomBuild
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at RunCustomBuild for rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
INFO:cargo::ops::cargo_rustc::job_queue:   end: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) RunCustomBuild
INFO:cargo::ops::cargo_rustc::job_queue: start: hi v0.1.0 (file:///private/tmp/hi) RunCustomBuild
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at RunCustomBuild for hi v0.1.0 (file:///private/tmp/hi)
INFO:cargo::ops::cargo_rustc::job_queue: start: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) Libraries
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at Libraries for rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
DEBUG:cargo::ops::cargo_rustc::job_queue: job: Fresh (Fresh)
INFO:cargo::ops::cargo_rustc::job_queue: start: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) LibraryTests
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at LibraryTests for rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
INFO:cargo::ops::cargo_rustc::job_queue:   end: hi v0.1.0 (file:///private/tmp/hi) RunCustomBuild
INFO:cargo::ops::cargo_rustc::job_queue:   end: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) Libraries
INFO:cargo::ops::cargo_rustc::job_queue: start: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) BinaryTests
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at BinaryTests for rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
INFO:cargo::ops::cargo_rustc::job_queue: start: hi v0.1.0 (file:///private/tmp/hi) LibraryTests
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at LibraryTests for hi v0.1.0 (file:///private/tmp/hi)
INFO:cargo::ops::cargo_rustc::job_queue: start: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) Binaries
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at Binaries for rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
INFO:cargo::ops::cargo_rustc::job_queue: start: hi v0.1.0 (file:///private/tmp/hi) Libraries
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at Libraries for hi v0.1.0 (file:///private/tmp/hi)
INFO:cargo::ops::cargo_rustc::job_queue:   end: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) LibraryTests
INFO:cargo::ops::cargo_rustc::job_queue:   end: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) BinaryTests
INFO:cargo::ops::cargo_rustc::job_queue:   end: hi v0.1.0 (file:///private/tmp/hi) LibraryTests
INFO:cargo::ops::cargo_rustc::job_queue:   end: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) Binaries
INFO:cargo::ops::cargo_rustc::job_queue: start: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) End
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at End for rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
INFO:cargo::ops::cargo_rustc::job_queue:   end: hi v0.1.0 (file:///private/tmp/hi) Libraries
INFO:cargo::ops::cargo_rustc::job_queue: start: hi v0.1.0 (file:///private/tmp/hi) Binaries
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at Binaries for hi v0.1.0 (file:///private/tmp/hi)
DEBUG:cargo::ops::cargo_rustc::job_queue: job: Fresh (Fresh)
INFO:cargo::ops::cargo_rustc::job_queue: start: hi v0.1.0 (file:///private/tmp/hi) BinaryTests
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at BinaryTests for hi v0.1.0 (file:///private/tmp/hi)
INFO:cargo::ops::cargo_rustc::job_queue:   end: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) End
INFO:cargo::ops::cargo_rustc::job_queue:   end: hi v0.1.0 (file:///private/tmp/hi) Binaries
INFO:cargo::ops::cargo_rustc::job_queue:   end: hi v0.1.0 (file:///private/tmp/hi) BinaryTests
INFO:cargo::ops::cargo_rustc::job_queue: start: hi v0.1.0 (file:///private/tmp/hi) End
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at End for hi v0.1.0 (file:///private/tmp/hi)
INFO:cargo::ops::cargo_rustc::job_queue:   end: hi v0.1.0 (file:///private/tmp/hi) End
DEBUG:cargo::ops::cargo_compile: compile; manifest-path=/private/tmp/hi/Cargo.toml
DEBUG:cargo::ops::cargo_compile: loaded package; package=hi v0.1.0 (file:///private/tmp/hi)
DEBUG:cargo::ops::cargo_compile: loaded config; configs={"registry": {"token": y8Q6qDz21k86bKpW2e5kPzFIwugLeq2q (from /Users/coreyf/.cargo/config)}}
DEBUG:cargo::core::resolver: activating hi v0.1.0 (file:///private/tmp/hi)
DEBUG:cargo::core::registry: load/missing  https://github.com/rust-lang/rustc-serialize#af910b74
INFO:cargo::sources::git::utils: update submodules for: "/Users/coreyf/.cargo/git/checkouts/rustc-serialize-bdc70357aa712c7d/master/"
DEBUG:cargo::core::resolver: activating rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
DEBUG:cargo::core::resolver: resolved: graph: Graph {
  - hi v0.1.0 (file:///private/tmp/hi)
    - rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
  - rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
}

features: {
}
DEBUG:cargo::core::resolver: activating hi v0.1.0 (file:///private/tmp/hi)
DEBUG:cargo::core::registry: load/match    https://github.com/rust-lang/rustc-serialize#af910b74
DEBUG:cargo::core::resolver: activating rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
DEBUG:cargo::core::resolver: resolved: graph: Graph {
  - hi v0.1.0 (file:///private/tmp/hi)
    - rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
  - rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
}

features: {
}
DEBUG:cargo::ops::cargo_rustc: compile_targets: hi v0.1.0 (file:///private/tmp/hi)
DEBUG:cargo::ops::cargo_rustc: compile_pkg; pkg=hi v0.1.0 (file:///private/tmp/hi)
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /private/tmp/hi/target/debug/.fingerprint/hi-585ac5373ba9154b/bin-hi
DEBUG:cargo::ops::cargo_rustc::fingerprint: extra Target { kind: Bin, name: "hi", src_path: "/private/tmp/hi/src/main.rs", metadata: None, tested: true, benched: true, doc: true, doctest: false, harness: true, for_host: false } Profile { opt_level: 0, lto: false, codegen_units: None, rustc_args: None, debuginfo: true, debug_assertions: true, rpath: false, test: false, doc: false } None = 0553f1644cff0529
DEBUG:cargo::ops::cargo_rustc::fingerprint: extra Target { kind: Lib([Lib]), name: "rustc-serialize", src_path: "/Users/coreyf/.cargo/git/checkouts/rustc-serialize-bdc70357aa712c7d/master/src/lib.rs", metadata: Some(Metadata { metadata: "d9cf16782a5152b9", extra_filename: "-d9cf16782a5152b9" }), tested: true, benched: true, doc: true, doctest: true, harness: true, for_host: false } Profile { opt_level: 0, lto: false, codegen_units: None, rustc_args: None, debuginfo: true, debug_assertions: true, rpath: false, test: false, doc: false } None = 415206d49530a1ff
DEBUG:cargo::ops::cargo_rustc::fingerprint: inputs: af910b74fbc7eb25b5e9f819af717b1abf029b34 415206d49530a1ff []
DEBUG:cargo::ops::cargo_rustc::fingerprint: inputs: 1434906638.000000000s 0553f1644cff0529 ["264fbf3ff4e1d079"]
DEBUG:cargo::ops::cargo_rustc: compile_pkg; pkg=rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint at: /private/tmp/hi/target/debug/.fingerprint/rustc-serialize-d9cf16782a5152b9/lib-rustc-serialize
DEBUG:cargo::ops::cargo_rustc::fingerprint: inputs: af910b74fbc7eb25b5e9f819af717b1abf029b34 415206d49530a1ff []
INFO:cargo::ops::cargo_rustc::job_queue: start: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) Start
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at Start for rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
DEBUG:cargo::ops::cargo_rustc::job_queue: job: Fresh (Fresh)
INFO:cargo::ops::cargo_rustc::job_queue: start: hi v0.1.0 (file:///private/tmp/hi) Start
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at Start for hi v0.1.0 (file:///private/tmp/hi)
DEBUG:cargo::ops::cargo_rustc::job_queue: job: Fresh (Fresh)
INFO:cargo::ops::cargo_rustc::job_queue:   end: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) Start
INFO:cargo::ops::cargo_rustc::job_queue: start: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) BuildCustomBuild
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at BuildCustomBuild for rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
INFO:cargo::ops::cargo_rustc::job_queue:   end: hi v0.1.0 (file:///private/tmp/hi) Start
INFO:cargo::ops::cargo_rustc::job_queue: start: hi v0.1.0 (file:///private/tmp/hi) BuildCustomBuild
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at BuildCustomBuild for hi v0.1.0 (file:///private/tmp/hi)
INFO:cargo::ops::cargo_rustc::job_queue:   end: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) BuildCustomBuild
INFO:cargo::ops::cargo_rustc::job_queue: start: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) RunCustomBuild
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at RunCustomBuild for rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
INFO:cargo::ops::cargo_rustc::job_queue:   end: hi v0.1.0 (file:///private/tmp/hi) BuildCustomBuild
INFO:cargo::ops::cargo_rustc::job_queue:   end: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) RunCustomBuild
INFO:cargo::ops::cargo_rustc::job_queue: start: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) Libraries
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at Libraries for rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
DEBUG:cargo::ops::cargo_rustc::job_queue: job: Fresh (Fresh)
INFO:cargo::ops::cargo_rustc::job_queue: start: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) LibraryTests
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at LibraryTests for rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
INFO:cargo::ops::cargo_rustc::job_queue: start: hi v0.1.0 (file:///private/tmp/hi) RunCustomBuild
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at RunCustomBuild for hi v0.1.0 (file:///private/tmp/hi)
INFO:cargo::ops::cargo_rustc::job_queue:   end: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) Libraries
INFO:cargo::ops::cargo_rustc::job_queue: start: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) Binaries
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at Binaries for rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
INFO:cargo::ops::cargo_rustc::job_queue: start: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) BinaryTests
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at BinaryTests for rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
INFO:cargo::ops::cargo_rustc::job_queue:   end: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) LibraryTests
INFO:cargo::ops::cargo_rustc::job_queue:   end: hi v0.1.0 (file:///private/tmp/hi) RunCustomBuild
INFO:cargo::ops::cargo_rustc::job_queue: start: hi v0.1.0 (file:///private/tmp/hi) LibraryTests
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at LibraryTests for hi v0.1.0 (file:///private/tmp/hi)
INFO:cargo::ops::cargo_rustc::job_queue: start: hi v0.1.0 (file:///private/tmp/hi) Libraries
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at Libraries for hi v0.1.0 (file:///private/tmp/hi)
INFO:cargo::ops::cargo_rustc::job_queue:   end: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) Binaries
INFO:cargo::ops::cargo_rustc::job_queue:   end: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) BinaryTests
INFO:cargo::ops::cargo_rustc::job_queue: start: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) End
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at End for rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74)
INFO:cargo::ops::cargo_rustc::job_queue:   end: hi v0.1.0 (file:///private/tmp/hi) LibraryTests
INFO:cargo::ops::cargo_rustc::job_queue:   end: hi v0.1.0 (file:///private/tmp/hi) Libraries
INFO:cargo::ops::cargo_rustc::job_queue: start: hi v0.1.0 (file:///private/tmp/hi) Binaries
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at Binaries for hi v0.1.0 (file:///private/tmp/hi)
DEBUG:cargo::ops::cargo_rustc::job_queue: job: Fresh (Fresh)
INFO:cargo::ops::cargo_rustc::job_queue: start: hi v0.1.0 (file:///private/tmp/hi) BinaryTests
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at BinaryTests for hi v0.1.0 (file:///private/tmp/hi)
INFO:cargo::ops::cargo_rustc::job_queue:   end: rustc-serialize v0.3.15 (https://github.com/rust-lang/rustc-serialize#af910b74) End
INFO:cargo::ops::cargo_rustc::job_queue:   end: hi v0.1.0 (file:///private/tmp/hi) Binaries
INFO:cargo::ops::cargo_rustc::job_queue:   end: hi v0.1.0 (file:///private/tmp/hi) BinaryTests
INFO:cargo::ops::cargo_rustc::job_queue: start: hi v0.1.0 (file:///private/tmp/hi) End
DEBUG:cargo::ops::cargo_rustc::job_queue: start Fresh at End for hi v0.1.0 (file:///private/tmp/hi)
INFO:cargo::ops::cargo_rustc::job_queue:   end: hi v0.1.0 (file:///private/tmp/hi) End
     Running `target/debug/hi`
thread '<main>' panicked at 'unexpected token Some(ObjectEnd)', /Users/coreyf/.cargo/git/checkouts/rustc-serialize-bdc70357aa712c7d/master/src/json.rs:1927
stack backtrace:
   1:        0x1008c9e45 - sys::backtrace::write::hb40a7a5e7a72988bfas
   2:        0x1008ccff4 - panicking::on_panic::h86479ea026bd45advvw
   3:        0x1008c6cb8 - rt::unwind::begin_unwind_inner::h293827e692145ff2Ndw
   4:        0x1008c6fbc - rt::unwind::begin_unwind_fmt::h50405e2d93950933Tcw
   5:        0x1008b4bc6 - json::Builder<T>::build::h9608899132882922979
   6:        0x1008c46c2 - json::Json::from_str::hf3f63141a48a0bf0X9k
   7:        0x1008a3b89 - main::h781db2a45f4d5b0fkaa
   8:        0x1008ce008 - rust_try_inner
   9:        0x1008cdff5 - rust_try
  10:        0x1008cd800 - rt::lang_start::h1547a6a6590823a3zqw
  11:        0x1008a966e - main
DEBUG:cargo: handle_error; err=CliError { error: Process didn't exit successfully: `target/debug/hi` (exit code: 101), unknown: true, exit_code: 101 }
An unknown error occurred

To learn more, run the command again with --verbose.
```
